title: Notebook
description: Notes about learning, toughts and experiments
remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
google_analytics: G-6DFY9REYGM
baseurl: /notebook
plugins:
  - jekyll-remote-theme 